### ISSUE TITLE
distacco carico con chiusura contatto

### ISSUE THREAD

**Issue by danygi79** [andbad/HA_PowerControl#4]
Ciao, ho installato il tuo package e tutto funziona correttamente ma per le mie esigenze ho la necessità che, per disattivare uno dei carichi, uno switch venga attivato al posto di essere disattivato.
Questo mi è necessario perchè uno dei carichi è la pompa di calore per il riscaldamento, che ha un suo contatto per la disattivazione momentanea, ma che và alimentato per bloccare la stessa.
C'è modo di intervenire sul codice per permettere questa impostazione?

**Comment by andbad** [comment]
Ti basta creare uno switch template che inverta lo stato dello switch della pompa di calore. Qualcosa del tipo:
```
switch:
  - platform: template
    switches:
      pompa_calore_invertito:
        value_template: >
            {% if states('switch.pompa_calore') == 'on' %}
              off
            {% else %}
              on
            {% endif %}
        turn_on:
          service: switch.turn_off
          target:
            entity_id: switch.pompa_calore
        turn_off:
          service: switch.turn_on
          target:
            entity_id: switch.pompa_calore
```

By(t)e
