### ISSUE TITLE
Relè a riposo in OFF

### ISSUE THREAD

**Issue by Frank079** [andbad/HA_PowerControl#56]
Buonasera 
ho installato la funzione dei controllo carichi e bene o male sono riuscito a farla funzionare.
Ho pochissima esperienza e chiedo a voi un aiuto se possibile.
Avrei necessità che i relè dei carichi nello stato di riposo sono in OFF, ho installato dei relè NC cosi non averli sempre attivi.
Poi sarebbe bello se possibile avere la scelta 

Grazie 
Franco

**Comment by andbad** [comment]
Puoi facilmente ottenere quello che chiedi creando uno [switch template](https://www.home-assistant.io/integrations/switch.template/) dove lo stato on corrisponde ad uno stato off del relè, ed utilizzarlo all'interno di PowerControl.

Qualcosa del tipo:
```
switch:
  - platform: template
    switches:
      carico:
        value_template: "{{ is_state('switch.rele_carico', 'off') }}"
        turn_on:
          action: switch.turn_off
          target:
            entity_id: switch.rele_carico
        turn_off:
          action: switch.turn_on
          target:
            entity_id: switch.rele_carico

```

(non l'ho testato ma dovrebbe funzionare).

By(t)e
