### ISSUE TITLE
Abilitazione spegnimento condizionatori integrati con TUYA

### ISSUE THREAD

**Issue by alex76m** [andbad/HA_PowerControl#57]
**Descrivi il problema che vorresti risolvere con una nuova funzionalità**
Ciao e grazie per l'impegno che hai verso tutti noi
ho un problema con condizionatori integrati in HA tramite TUYA  ti spiego:
ho collegato i condizionatori su degli shelly plus per avere il sensore di consumo istantaneto ma non riesco a consigurare lo spegnimento senza spegnere lo shelly togliendo la corrente a tutto e non penso sia il caso

**La tua soluzione**
sperando che già ti sia capitato cosi mi puoi (se Vuoi) aiutarmi

![Image](https://github.com/user-attachments/assets/16cd97bd-9f01-4246-9d61-3ced0e896624)

**Comment by andbad** [comment]
Il modo più semplice è creare uno switch template:
```
switch:
  - platform: template
    switches:
      condizionatore_salone_soft:
        value_template: "{{ states('climate.condizionatore_salone') }}"
        turn_on:
          action: climate.turn_on
          target:
            entity_id: climate.condizionatore_salone
        turn_off:
          action: climate.turn_off
          target:
            entity_id: climate.condizionatore_salone
```
[Ovviamente adegua il nome dell'entità climate con quella che corrisponde alla tua entità, ho tirato ad indovinare]
Poi in HA_PowerControl vai a configurare come interruttore quello appena creato, che si chiamerà switch.condizionatore_salone_soft (o come deciderai di chiamarlo).

Fammi sapere.

By(t)e
